'use client';

import { useEffect, useState } from 'react';
import { ArrowRight, Bot, Check, LockKeyhole, Radar, ShieldCheck, Sparkles } from 'lucide-react';
import { TradingDashboard, type AuthSession } from '@/components/trading-dashboard';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';

const ADMIN = { email: 'admin@wisefx.ai', password: 'WiseFX@Admin11' };
const MEMBER = { email: 'member@wisefx.ai', password: 'WiseFX@Member11' };

function Brand() {
  return <span className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl border border-emerald-300/40 bg-emerald-400/10 font-black text-emerald-300">W</span><span><b className="block tracking-[.08em]">WiseFX AI</b><small className="block text-xs tracking-[.15em] text-zinc-500">智汇AI</small></span></span>;
}

function Landing({ onAuthenticated }: { onAuthenticated: (session: AuthSession) => void }) {
  const [open,setOpen]=useState(false);
  const [mode,setMode]=useState<'login'|'register'>('login');
  const [name,setName]=useState('新会员');
  const [email,setEmail]=useState(ADMIN.email);
  const [password,setPassword]=useState(ADMIN.password);
  const [message,setMessage]=useState('');
  const [busy,setBusy]=useState(false);
  const openLogin=()=>{setMode('login');setEmail(ADMIN.email);setPassword(ADMIN.password);setMessage('');setOpen(true)};
  const submit=async()=>{setBusy(true);setMessage('');try{const endpoint=mode==='login'?'/api/v1/auth/login':'/api/v1/auth/register';const body=mode==='login'?{email,password}:{name,email,password};const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json() as AuthSession&{detail?:string};if(!res.ok){setMessage(data.detail??'操作失败');return}onAuthenticated(data)}catch{setMessage('服务暂时无法连接')}finally{setBusy(false)}};
  const fill=(account:typeof ADMIN)=>{setMode('login');setEmail(account.email);setPassword(account.password);setMessage('')};
  return <main className="min-h-screen overflow-hidden">
    <header className="relative z-20 border-b bg-[#070a08]/85 backdrop-blur-xl"><div className="mx-auto flex min-h-16 max-w-7xl items-center justify-between px-4 sm:min-h-20 sm:px-5"><a href="#top" aria-label="WiseFX AI 首页"><Brand/></a><nav className="hidden items-center gap-8 text-sm text-zinc-400 md:flex"><a href="#features" className="hover:text-white">产品能力</a><a href="#pricing" className="hover:text-white">版本价格</a><a href="#security" className="hover:text-white">安全机制</a></nav><Button size="sm" className="sm:hidden" onClick={openLogin}>登录<ArrowRight/></Button><Button className="hidden sm:inline-flex" onClick={openLogin}>登录控制台<ArrowRight/></Button></div></header>
    <section id="top" className="relative mx-auto grid max-w-7xl items-center gap-12 px-4 py-14 sm:min-h-[680px] sm:px-5 sm:py-20 lg:grid-cols-[1.05fr_.95fr]"><div className="pointer-events-none absolute left-1/2 top-10 h-80 w-80 max-w-full -translate-x-1/2 rounded-full bg-emerald-400/10 blur-[100px] sm:h-96 sm:w-96"/><div className="relative"><Badge className="mb-5 border-emerald-300/25 bg-emerald-400/10 text-emerald-200 sm:mb-6" variant="outline"><Sparkles/>V1.1 开发演示版</Badge><h1 className="max-w-3xl text-4xl font-black leading-[1.08] tracking-[-.045em] sm:text-6xl lg:text-7xl">让 AI 看懂行情，<span className="text-emerald-300">让风控决定执行。</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-zinc-400 sm:mt-7 sm:text-lg sm:leading-8">WiseFX AI 将 MT5 行情、结构化 AI 决策与 EA 本地硬风控连接在一起。每一次判断有依据，每一次执行有边界。</p><div className="mt-8 grid gap-3 sm:mt-9 sm:flex sm:flex-wrap"><Button size="lg" className="w-full sm:w-auto" onClick={openLogin}>进入演示控制台<ArrowRight/></Button><Button size="lg" className="w-full sm:w-auto" variant="outline" onClick={()=>document.querySelector('#features')?.scrollIntoView({behavior:'smooth'})}>了解产品能力</Button></div><div className="mt-8 grid gap-3 text-sm text-zinc-500 sm:mt-10 sm:flex sm:flex-wrap sm:gap-x-8"><span className="flex items-center gap-2"><Check className="size-4 text-emerald-300"/>默认观察模式</span><span className="flex items-center gap-2"><Check className="size-4 text-emerald-300"/>AI异常自动 HOLD</span><span className="flex items-center gap-2"><Check className="size-4 text-emerald-300"/>完整决策审计</span></div></div>
      <div className="relative"><div className="absolute -inset-8 rounded-full bg-emerald-400/10 blur-3xl"/><Card className="terminal-card relative overflow-hidden border-emerald-300/20 p-0"><div className="flex items-center justify-between border-b px-5 py-4"><div className="flex items-center gap-2 text-sm font-semibold"><span className="size-2 rounded-full bg-emerald-400 shadow-[0_0_12px_#62efa7]"/>AI 决策链路</div><Badge variant="outline">OBSERVE</Badge></div><CardContent className="p-5"><div className="mb-5 grid grid-cols-3 gap-2 text-center"><div className="rounded-xl border bg-white/[.02] p-3"><small className="text-zinc-500">品种</small><b className="mt-1 block">XAUUSD</b></div><div className="rounded-xl border bg-white/[.02] p-3"><small className="text-zinc-500">置信度</small><b className="number mt-1 block text-emerald-300">72%</b></div><div className="rounded-xl border bg-white/[.02] p-3"><small className="text-zinc-500">结论</small><b className="mt-1 block text-amber-200">观望</b></div></div>{[['行情快照','已接收'],['多周期结构','已计算'],['DeepSeek 分析','已完成'],['硬风控校验','通过'],['EA 执行许可','未签发']].map(([label,state],index)=><div key={label} className="flex items-center gap-4 border-t py-4 first:border-t-0"><span className={`grid size-8 place-items-center rounded-full text-xs font-bold ${index<4?'bg-emerald-400/10 text-emerald-300':'bg-amber-400/10 text-amber-200'}`}>{index+1}</span><span className="flex-1 text-sm text-zinc-400">{label}</span><b className="text-sm">{state}</b></div>)}</CardContent></Card></div>
    </section>
    <section id="features" className="border-y bg-black/20"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-5 sm:py-24"><p className="mb-3 text-sm font-semibold uppercase tracking-[.2em] text-emerald-300">Product system</p><h2 className="max-w-2xl text-3xl font-bold sm:text-4xl">不是把聊天机器人接到下单按钮</h2><div className="mt-8 grid gap-3 sm:mt-10 md:grid-cols-2 lg:grid-cols-4">{[[Radar,'市场结构','多周期行情、波动与价格结构统一分析。'],[Bot,'结构化决策','AI 只输出固定格式的候选计划，拒绝自由指令。'],[ShieldCheck,'硬风控','仓位、回撤、点差与执行许可由确定性规则控制。'],[LockKeyhole,'RBAC 权限','管理员与会员权限隔离，敏感操作服务端鉴权。']].map(([Icon,title,copy])=>{const I=Icon as typeof Radar;return <Card key={title as string} className="terminal-card"><CardContent className="p-5"><I className="mb-6 size-8 text-emerald-300 sm:mb-8"/><h3 className="text-lg font-semibold">{title as string}</h3><p className="mt-3 leading-7 text-zinc-500">{copy as string}</p></CardContent></Card>})}</div></div></section>
    <section id="pricing" className="mx-auto max-w-7xl px-4 py-16 sm:px-5 sm:py-24"><div className="text-center"><p className="mb-3 text-sm font-semibold uppercase tracking-[.2em] text-emerald-300">Pricing</p><h2 className="text-3xl font-bold sm:text-4xl">从验证开始，再进入自动执行</h2><p className="mt-4 text-zinc-500">开发演示阶段暂不收取费用，以下为计划中的商业版本。</p></div><div className="mx-auto mt-8 grid max-w-4xl gap-4 sm:mt-10 md:grid-cols-2"><Card className="terminal-card"><CardContent className="p-5 sm:p-7"><Badge variant="outline">体验版</Badge><div className="number mt-6 text-4xl font-bold">免费</div><p className="mt-3 text-zinc-500">14天模拟盘验证</p><ul className="mt-7 space-y-3 text-sm text-zinc-300">{['1个模拟账户','AI 行情分析','安全观察模式','基础决策记录'].map(x=><li key={x} className="flex gap-2"><Check className="size-4 text-emerald-300"/>{x}</li>)}</ul><Button className="mt-8 w-full" variant="outline" onClick={openLogin}>立即体验</Button></CardContent></Card><Card className="terminal-card border-emerald-300/35"><CardContent className="p-5 sm:p-7"><div className="flex justify-between"><Badge>Pro</Badge><span className="text-xs text-emerald-300">计划上线</span></div><div className="number mt-6 text-4xl font-bold">¥199<span className="text-base font-normal text-zinc-500"> / 月</span></div><p className="mt-3 text-zinc-500">个人交易者完整版本</p><ul className="mt-7 space-y-3 text-sm text-zinc-300">{['1个实盘账户','人工确认与自动模式','高级风险控制','完整交易复盘'].map(x=><li key={x} className="flex gap-2"><Check className="size-4 text-emerald-300"/>{x}</li>)}</ul><Button className="mt-8 w-full" onClick={openLogin}>进入演示</Button></CardContent></Card></div></section>
    <section id="security" className="border-t bg-black/20"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 px-5 py-16 md:flex-row md:items-center"><div><h2 className="text-2xl font-bold">资金始终留在你的交易账户</h2><p className="mt-3 max-w-2xl text-zinc-500">WiseFX AI 不接收客户资金。API中断、模型异常或计划过期时，系统默认拒绝新开仓。</p></div><Button variant="outline" onClick={openLogin}>查看风控控制台</Button></div></section>
    <footer className="mx-auto flex max-w-7xl flex-col gap-5 px-4 py-8 text-sm text-zinc-600 sm:flex-row sm:flex-wrap sm:items-center sm:justify-between sm:px-5"><Brand/><span>© 2026 WiseFX AI · AI生成内容仅供辅助分析，不构成投资建议</span></footer>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[calc(100dvh-1rem)] w-[calc(100%-1rem)] overflow-y-auto sm:max-w-md"><DialogHeader><DialogTitle>{mode==='login'?'登录 WiseFX AI':'注册会员账户'}</DialogTitle><DialogDescription>{mode==='login'?'演示账号已默认填写，可直接登录查看不同权限。':'注册后默认获得 MEMBER 会员角色。'}</DialogDescription></DialogHeader><div className="space-y-3">{mode==='register'&&<Input value={name} onChange={e=>setName(e.target.value)} placeholder="姓名"/>}<Input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="邮箱"/><Input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="密码（至少8位）" onKeyDown={e=>{if(e.key==='Enter')void submit()}}/>{message&&<p className="text-sm text-red-300">{message}</p>}<Button className="w-full" disabled={busy} onClick={()=>void submit()}>{busy?'正在验证…':mode==='login'?'登录控制台':'创建会员账户'}</Button></div><div className="rounded-xl border bg-white/[.02] p-3 text-xs text-zinc-500"><div className="mb-2 flex flex-wrap gap-3"><button className="min-h-8 text-emerald-300 hover:underline" onClick={()=>fill(ADMIN)}>管理员演示</button><button className="min-h-8 text-emerald-300 hover:underline" onClick={()=>fill(MEMBER)}>会员演示</button></div><p className="break-all">{ADMIN.email} / {ADMIN.password}</p><p className="mt-1 break-all">{MEMBER.email} / {MEMBER.password}</p></div><button className="min-h-10 text-sm text-zinc-500 hover:text-white" onClick={()=>{setMode(mode==='login'?'register':'login');setMessage('')}}>{mode==='login'?'没有账户？注册会员':'已有账户？返回登录'}</button></DialogContent></Dialog>
  </main>;
}

export function WiseApp() {
  const [session,setSession]=useState<AuthSession|null>(null);
  useEffect(()=>{void fetch('/api/v1/auth/me').then(async res=>{if(res.ok)setSession(await res.json() as AuthSession)})},[]);
  const logout=async()=>{if(session)await fetch('/api/v1/auth/logout',{method:'POST',headers:{'X-CSRF-Token':session.csrf_token}});setSession(null)};
  return session?<TradingDashboard session={session} onLogout={()=>void logout()}/>:<Landing onAuthenticated={setSession}/>;
}
